### PR TITLE
Updated poster design

### PR DESCRIPTION
**Pull request by peconia**
Changed the font and style of some posters and added ponies. We printed these posters for the workshop at Pycon UK in Coventry.
:horse: :zap: :heart_decoration:

### CODE REVIEW

**Comment by patjouk** [comment]
The posters are really cool but I'm not sure it's a good idea to add those in our repository: I fear that people will use the cute PyconUK crowned pony for other events.
Any other opinions on this?

**Comment by peconia** [comment]
Would it be better if i change them to versions without the crown but otherwise the same?

**Comment by patjouk** [comment]
It's a awesome idea! Can you do that?

**Comment by peconia** [comment]
Done! I changed the posters to the Sheffield versions with no crowns :).

**Comment by patjouk** [comment]
Awesome :heart_eyes_cat: Thanks a lot!

**Pull request merged**
