### PR TITLE
dg ensenada graphics

### PR DESCRIPTION
**Pull request by andyosuna**
:smiley:

### CODE REVIEW

**Comment by olasitarska** [comment]
Thanks Andrea! Could you also add .svg format? This allows for editing for folks without Illustrator. I believe you can just export it from .ai files :)

**Comment by williln** [comment]
Thanks so much! Can't wait to fork and use :)

**Comment by olasitarska** [comment]
@andyosuna I'm merging that now, it'd be awesome if you could export to svg and upload them to one day! :panda_face: :heartbeat:

**Comment by andyosuna** [comment]
Hey, sorry about that, its just that Laura has the power! (she has the laptop with adobe). Soon, promise :cake:

**Pull request merged**
