### PR TITLE
Revert 1 brno feb 05

### PR DESCRIPTION
**Pull request by thatdocslady**

### CODE REVIEW

**Comment by bmispelon** [comment]
Wrong button :) :dancer:

**Comment by thatdocslady** [comment]
Wrong repo, actually ;-)

I still need to nail down the forked/origin instinct.

Did I break anything?

**Comment by bmispelon** [comment]
Not that I'm aware of... :bomb:

**Comment by thatdocslady** [comment]
well I noticed that the pull request was opened to the wrong repo, closed
it, and now it doesn't show up there anymore, so I guess no harm done. Now
I just need to figure out how to cherry-pick updates from the upstream to
my fork without making a mess, but that's a lesson for another day ;-)

On Tue, Feb 10, 2015 at 3:47 PM, Baptiste Mispelon <notifications@github.com

**Comment by bmispelon** [comment]
`git pull upstream master` should do the trick to keep your fork up to date (assuming you called the upstream repository "upstream").
This will fetch the commit from upstream and merge them in the current branch, creating a merge commit if needed.

**Comment by thatdocslady** [comment]
Dammit! I did it again.. I'll figure it out, don't worry. And yes, I set
the upstream name to "upstream".

On Tue, Feb 10, 2015 at 3:53 PM, Baptiste Mispelon <notifications@github.com

**Pull request closed without merging**
